import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// 本番ビルド（npm run build）は、自動審査・CI・deploy が使う。
// 環境によって結果や副作用が変わらないよう、環境変数も .env.local も見ない。
// 監視ビルド（npm run dev）だけ、OBSIDIAN_DEV_PLUGIN_DIR の確認用の Vault へコピーする。
// 実運用の Vault（OBSIDIAN_PLUGIN_DIR）へは npm run deploy からしか入れない。
// scripts/lib は dev のときだけ読み込む。審査の環境の Node の版は分からないので、
// 本番ビルドが新しい Node の API（util.parseEnv）に依存しないようにする。
const plugins = [];
if (!prod) {
	const { loadLocalEnv } = await import('./scripts/lib/env.mjs');
	const { copyPluginFiles } = await import('./scripts/lib/copyPluginFiles.mjs');
	loadLocalEnv();
	const devDir = process.env.OBSIDIAN_DEV_PLUGIN_DIR;
	if (devDir) {
		plugins.push({
			name: 'copy-to-dev-vault',
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length > 0) return;
					try {
						copyPluginFiles(devDir);
						console.log(`copied to ${devDir}`);
					} catch (error) {
						// 監視ビルドは止めない。設定の誤りを出して次のビルドを待つ
						console.error(`[copy-to-dev-vault] ${error.message}`);
					}
				});
			},
		});
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
